language: dart

dart:
- stable

dart_task:
- test: --platform vm
  xvfb: false
- dartanalyzer: true
- dartfmt: true

notifications:
  email:
    recipients:
      - julemand101@archlinux.dk
    on_success: always
    on_failure: always
