language: dart
os: linux

dart:
- stable

dart_task:
- test: --platform vm
  xvfb: false
- dartanalyzer: --fatal-warnings
- dartfmt

notifications:
  email:
    recipients:
      - julemand101@archlinux.dk
    on_success: always
    on_failure: always
