name: advent_of_code_2019
description: Solutions for Advent of Code 2019.
version: 0.0.1
homepage: http://www.archlinux.dk
author: Jacob Bang <julemand101@archlinux.dk>

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dev_dependencies:
  extra_pedantic: ^1.4.0
  test: ^1.17.4
